[Group 3] Adding agent and sign detection
krishauser/GEMstack pull request #69
Opened 2024-05-06 01:46 UTC by vishakhsuresh98

This PR adds the road driving group's agent and sign detectors.

Types of objects detected:
- Agents (pedestrians and vehicles)
  - 5 classes of agents
  - PEDESTRIAN, BICYCLIST, CAR, MEDIUM_TRUCK, LARGE_TRUCK
- Signs (road signs and traffic lights):
  - 7 types of road signs and 3 types of signals
  - Signs include: NO_LEFT_TURN, NO_RIGHT_TURN, NO_U_TURN, NO_PARKING, PEDESTRIAN_CROSSING, RAILROAD_CROSSING, STOP_SIGN
  - Signals: GREEN, YELLOW, RED

2024-05-06 03:08 UTC, krishauser requested changes
There are a few config paths that should be changed.

2024-05-06 03:08 UTC, krishauser commented on GEMstack/knowledge/defaults/current.yaml
These paths should go in then gem_e4 yaml file in the vehicle directory

2024-05-06 03:08 UTC, krishauser commented on GEMstack/onboard/perception/object_detection.py
How does this interact with the detection logic from group 4?

2024-05-06 03:28 UTC, vishakhsuresh98 commented on GEMstack/knowledge/defaults/current.yaml
Moved them to `calibration/gem_e4.yaml`.
Should they be in `vehicle/gem_e4.yaml`?

2024-05-06 03:44 UTC, vishakhsuresh98 commented on GEMstack/onboard/perception/object_detection.py
`object_detection.py` does not interact with group 4's code. 

It contains most of the code common to our agent and sign detectors. More specifically, it creates a `PhysicalObject` (placed in the current frame) for each object of interest. Our agent and sign detectors use that to create an `AgentState` or `Sign` object.

Differences between the 2 versions include: 
- the object detector uses spatial clustering to identify the lidar points corresponding to a bounding box,
- our agent detector handles more classes of objects

2024-05-06 19:51 UTC, krishauser requested changes

2024-05-06 19:51 UTC, krishauser commented on GEMstack/knowledge/calibration/gem_e4.yaml
Please be more specific about which “intrinsic” this is. There are 5 cameras.

2024-05-06 20:21 UTC, vishakhsuresh98 commented on GEMstack/knowledge/calibration/gem_e4.yaml
Moved `intrinsic` to `calibration/gem_e4_oak.yaml`.
Renamed `lidar_to_camera` as `lidar_to_oak`.

2024-05-07 02:51 UTC, krishauser approved these changes

2024-05-07 02:51 UTC, krishauser commented on GEMstack/knowledge/calibration/gem_e4.yaml
That works!

2024-05-07 02:51 UTC, merged