dynamic model for acceleration and parameter for future use
krishauser/GEMstack pull request #80
Opened 2024-05-07 17:55 UTC by obica-ai

a66b0e986d4b6918f4a3b8d279eaa7f2dd9eda04

the vehicle is following the acceleration model "group8_v1" on May,6 highbay day.
we tried to implement the dynamic model inside of MPC, but we find out the execution time is too expensive, thus we implement
the dynamic model towards the output of MPC, which is acceleration and steering wheel angle (not yet).

there are some TODO comment should be useful for future

2024-05-08 04:56 UTC, krishauser requested changes

2024-05-08 04:56 UTC, krishauser commented on GEMstack/knowledge/vehicle/dynamics.py
Why is there a gear above 1? This is absolutely inappropriate for our vehicles. Have you tested this?

2024-05-08 16:52 UTC, obica-ai commented on GEMstack/knowledge/vehicle/dynamics.py
I have removed it

2024-05-10 14:58 UTC, krishauser requested changes

2024-05-10 14:58 UTC, krishauser commented on GEMstack/state/trajectory.py
First, var_speed_arc_length_parameterize is not named correctly. If you deviate from arc length then you shouldn't call it arc_length. Since you are generating a speed profile, you should name it something like curvature_based_speed_parameterize.  

Second, the magic constants of 3, 5, 0.6, and 0.2 should be named something meaningful and provided as arguments.  I have not seen a report or demo about what these do. The final presentation did not do a good job of communicating that this is a useful function.

2024-05-11 14:11 UTC, krishauser commented
Low quality PR, not approved.

2024-05-11 14:11 UTC, closed without merging