S2024 simulation
krishauser/GEMstack pull request #88
Opened 2024-05-09 01:17 UTC by hermya

This PR contains:
Test recorder and route generator with cmd args
Test replayer with cmd args
Launch file to run test in carla
misc notes in pure-pursuit

2024-05-09 11:50 UTC, krishauser reviewed
I am concerned about the commented out code changing the trajectory tracker for testing in Carla. What is the problem using the standard tracker?

2024-05-10 00:09 UTC, hermya commented
> I am concerned about the commented out code changing the trajectory tracker for testing in Carla. What is the problem  using the standard tracker?

- The route generated in CARLA doesn't have intermediate points in lane change situations.
- In our demo video, if you seek to 1:43, you'll see a break in the line (Which appears weird in the graph, but the y-axis is zoomed out heavily). That is a lane change. In pure pursuit, we look at points in the path in the limits of -5 and +5. 
- Since the point after the lane change was far away, the car would run in circles around itself before reaching the last point before the lane change. 
- Keeping it 0 to 20 does the work

2024-05-10 02:19 UTC, krishauser commented
This should not be a problem if the trajectory was discretized finely enough (you can use existing methods for this) or the trajectory closest point query found the closest point within a segment. I do not approve this workaround.

2024-05-10 06:45 UTC, hermya commented
> This should not be a problem if the trajectory was discretized finely enough (you can use existing methods for this) or the trajectory closest point query found the closest point within a segment. I do not approve this workaround.

I understand
I'll add a code to modify CARLA route itself (trace more points between lane shifts), so this workaround is not necessary

2024-05-10 18:22 UTC, hermya commented
> This should not be a problem if the trajectory was discretized finely enough (you can use existing methods for this) or the trajectory closest point query found the closest point within a segment. I do not approve this workaround.

I've added code to generate internal fine points in the CARLA side, Here's the difference in how the points look when plotted:
Previous:
![before](https://github.com/krishauser/GEMstack/assets/62691524/a10048ac-b77c-46e0-85fe-89680f61f5e3)
Now:
![after](https://github.com/krishauser/GEMstack/assets/62691524/809b2306-3dba-4f9f-ad31-45e590b95a51)

Please note: The routes in both images are different but the lane change scenario is similar

2024-05-11 14:09 UTC, krishauser requested changes

2024-05-11 14:09 UTC, krishauser commented on GEMstack/onboard/planning/pure_pursuit.py
Indentation problem

2024-05-11 14:09 UTC, krishauser commented on testing/recordings/new-5.json
These recordings need more descriptive names. It is impossible for others to understand what they mean when they are named things like “new-5”

2024-05-11 16:13 UTC, hermya commented on testing/recordings/new-5.json
I'll change the names for the existing recording files. Also
the names of recordings can be controlled by the cmd arg: prefix
running test_recorder.py as:
_**python test_recorder.py --prefix=new-5**_
will create a new recording json and route csv file with new-5 name.

2024-05-11 21:12 UTC, hermya commented
I've solved the above requests, please let me know if any other changes are expected

2024-05-12 20:18 UTC, krishauser approved these changes
Removed temp file. Otherwise approved

2024-05-12 20:18 UTC, merged